<div>

<h3>Search & Update Keywords</h3>


<div id="keyword-form-pane">

</div>


<div id="keyword-list-pane">

</div>


</div>

<script type="text/javascript">
  
$.get('/application/content/keywordFormPane', function(response) {
  $('#keyword-form-pane').html(response);

  $.get('/application/content/keywordListPane', function(response) {
    $('#keyword-list-pane').html(response);
  });

});



</script>