<div class="row">
    <div class="col-lg-12">
        <section class="panel">
            <header class="panel-heading">
				Search & Update Keywords
                <span class="tools pull-right">
                    <a href="javascript:;" class="fa fa-chevron-down"></a>
                </span>
            </header>
            <div id="panel-inside" class="panel-body">
				<div id="keyword-form-pane">

				</div>
				<div id="keyword-list-pane">

				</div>				
            </div>
        </section>
    </div>
</div>



<div>

<h3>Search & Update Keywords</h3>


<div id="keyword-form-pane">

</div>


<div id="keyword-list-pane">

</div>


</div>

<script type="text/javascript">
  
$.get('/application/content/keywordFormPane', function(response) {
  $('#keyword-form-pane').html(response);

  $.get('/application/content/keywordListPane', function(response) {
    $('#keyword-list-pane').html(response);
  });

});



</script>