<div id="stats-pane">

	<section id="container" class="">
      
      <section id="main-content">
              <!-- page start-->
              
              <div class="row">

                  <div class="col-lg-12">
                      <section class="panel">
                          <header class="panel-heading">
                              İçerikleri Filtrele
                              <span class="tools pull-right">
                                <a href="javascript:;" class="fa fa-chevron-down"></a>
                            </span>
                          </header>
                          <div class="panel-body">
                              <form class="form-inline" role="form">
                                   <div class="form-group">
                                        <label class="control-label col-md-2" style="margin-top:6px">Tarih:</label>
                                        <div class="col-md-8">
											<select>
												<option value="1 Gün">1 Gün</option>
												<option value="1 Hafta">1 Hafta</option>
												<option value="2 Hafta">2 Hafta</option>
												<option value="3 Hafta">3 Hafta</option>
												<option value="4 Hafta">4 Hafta</option>
												<option value="1 Ay">1 Ay</option>
												<option value="1 yıl">1 yıl</option>
											  </select>
										</div>
                                      </div>
									  <div class="form-group">
                                          <label class="control-label col-md-2" style="margin-top:6px">Kaynak:</label>
                                          <div class="col-md-8">
                                              <select>
												<option value="facebook">Facebook</option>
												<option value="twitter">Twitter</option>
												<option value="eksisozluk">EkşiSözlük</option>
												<option value="rss">RSS</option>
											  </select>
                                          </div>
                                      </div>
                                  <div class="checkbox">
                                      <label>
                                          <input type="checkbox"> İşlenmiş
                                      </label>
                                  </div>
                                 <div class="checkbox">
                                      <label>
                                          <input type="checkbox"> İşlenmemiş
                                      </label>
                                  </div>
                              </form>
							  <div id="panel-inside">
								
							  </div>
                          </div>
                      </section>

                  </div>
              </div>
			<div class="row" id="records">
                <div class="col-sm-12">
              <section class="panel">
             <header class="panel-heading panel-red">
                              İşlemler
                              <span class="tools pull-right">
                                <a href="javascript:;" class="fa fa-chevron-down"></a>
                            </span>
                          </header>
              <div class="panel-body">
              <div class="adv-table">
				  <table  class="display table table-bordered table-striped">
				  <thead>
				  <tr>
					  <th>Kaynak</th>
					  <th>İçerik</th>
					  <th>Yazar</th>
					  <th>Tarih</th>
					  <th>Vaziyet</th>
				  </tr>
				  </thead>
				  <tbody id="insideHtml">
				 
				  </tbody>
				  
				  </table>
			  
              </div>
			  <div>
				<ul id="paginationBlock" class="pagination">
					
				</ul>
			  </div>
              </div>
			  
              </section>
              </div>
              </div>
              <!-- page end-->
      </section>
      <!--main content end-->
      <!--footer start-->
     
      <!--footer end-->
  </section>

</div>

<script type="text/javascript">

	$(function() {
		$.get('/application/content/searchFormPane', function(result) {
			$("#panel-inside").html(result);
		});
		
		$( "#panel-inside" ).on( "click", ".search-keyword", function() {
		  if($(this).attr('data-selected') == 'selected') {
			$(this).attr('data-selected', '');
			$(this).removeClass('selected-keyword');
		  } else {
			$(this).attr('data-selected', 'selected');
			$(this).addClass('selected-keyword');
		  }
		});
		$( "#panel-inside" ).on( "click", "#search-button", function() {
			loadSearchResults(0);
		});
		function loadSearchResults(from) {
			var items = [];
			$('#search-form>ul').children().each(function(el) {
			  if($(this).children('a').attr('data-selected') == 'selected')
				items.push($(this).children('a').attr('data-keyword'));
			});
			
			if($('#form-keyword-custom').val().length > 2)
			  items.push($('#form-keyword-custom').val());
		  
			$.getJSON('/application/content/searchResultsPane', {keywords: items.join(','), from: from}, function(data) {
				var bodyHtml = "", paginationHtml = "", clas = "";
				$.each(data.body, function(index, element) {
					bodyHtml += '<tr class="gradeA '+element.c+'">';
					bodyHtml += '<td class="typeof">'+element.s+'</td>';
					bodyHtml += '<td class="typeof">'+element.b+'</td>';
					bodyHtml += '<td class="nameof">'+element.a+'</td>';
					bodyHtml += '<td class="dateof">'+element.t+'</td>';
					bodyHtml += '<td class="typeof">';
					bodyHtml += '<p><input type="radio" name="inl" value="pot"> Pozitif</p>';
					bodyHtml += '<p><input type="radio" name="inl" class="not" value="not"> Nötr</p>';
					bodyHtml += '<p><input type="radio" name="inl" class="neg" value="negatif"> Negatif</p>';
					bodyHtml += '</td>';
					bodyHtml += '</tr>';
				});
				$('#insideHtml').html(bodyHtml);
				
				if(data.pageNow > 0) paginationHtml += linkCreator("", (data.pageNow - 1) * 10, "<");
				$.each(data.paginationLinks, function(index, element) {
					clas = "";
					if(element == data.pageNow) clas = ' class="active"';
					paginationHtml += linkCreator(clas, element * 10, element);
				});
				if(data.pageNow < data.pageTotal - 1) paginationHtml += linkCreator("", (data.pageNow + 1) * 10, ">");
				$("#paginationBlock").html(paginationHtml);
				
				$("html, body").animate({ scrollTop: $('#records').offset().top }, 300);
				
			});
		}
	
		function linkCreator(clas, numberData, fromData) {
			return '<li' + clas + '><a from-data="' + numberData + '" class="paglinks">' + fromData + '</a></li>';
		}
		
		$( "#paginationBlock" ).on( "click", ".paglinks", function() {
			var fromData = $(this).attr("from-data");
			loadSearchResults(fromData);
		});
		
	});

</script>