
	<div class="row">
                  <div class="col-lg-12">
                      <section class="panel">
                          <header class="panel-heading">
                              İçerikleri Filtrele
                              <span class="tools pull-right">
                                <a href="javascript:;" class="fa fa-chevron-down"></a>
                                
                            </span>
                          </header>
                          <div id="panel-inside" class="panel-body">
							<!--
                              <form class="form-inline" role="form">
                                   <div class="form-group">
                                          <label class="control-label col-md-2" style="margin-top:6px">Tarih:</label>
                                          <div class="col-md-8">
                                              <div id="spinner1">
                                                  <div class="input-group input-small">
                                                      <input type="text" class="spinner-input form-control" maxlength="3" readonly>
                                                      <div class="spinner-buttons input-group-btn btn-group-vertical">
                                                          <button type="button" class="btn spinner-up btn-xs btn-default">
                                                              <i class="fa fa-angle-up"></i>
                                                          </button>
                                                          <button type="button" class="btn spinner-down btn-xs btn-default">
                                                              <i class="fa fa-angle-down"></i>
                                                          </button>
                                                      </div>
                                                  </div>
                                              </div>
                                             
                                          </div>
                                      </div>
									  <div class="form-group">
                                          <label class="control-label col-md-2" style="margin-top:6px">Kaynak: </label>
                                          <div class="col-md-8">
                                              <div id="spinner1">
                                                  <div class="input-group input-small">
                                                      <input type="text" class="spinner-input form-control" maxlength="3" readonly>
                                                      <div class="spinner-buttons input-group-btn btn-group-vertical">
                                                          <button type="button" class="btn spinner-up btn-xs btn-default">
                                                              <i class="fa fa-angle-up"></i>
                                                          </button>
                                                          <button type="button" class="btn spinner-down btn-xs btn-default">
                                                              <i class="fa fa-angle-down"></i>
                                                          </button>
                                                      </div>
                                                  </div>
                                              </div>
                                             
                                          </div>
                                      </div>
                                  <div class="checkbox">
                                      <label>
                                          <input type="checkbox"> İşlenmiş
                                      </label>
                                  </div>
                                 <div class="checkbox">
                                      <label>
                                          <input type="checkbox"> İşlenmemiş
                                      </label>
                                  </div>
                              </form>
							-->
                          </div>
                      </section>

                  </div>
              </div>
			  
	<div class="row" id="records">
        <div class="col-sm-12">
            <section class="panel">
				<header class="panel-heading panel-red">
                              İcerikler
                              <span class="tools pull-right">
                                <a id="upDown" href="javascript:;" class="fa fa-chevron-down"></a>
                                
                            </span>
                          </header>
              <div class="panel-body">
              <div class="adv-table">
				  <table  class="display table table-bordered table-striped">
					<thead>
						<tr><th>Kaynak</th><th>İçerik</th><th>Yazar</th><th>Tarih</th></tr>
					</thead>
					<tbody id="insideHtml">
						<tr class="gradeA odd">
							<td class="  sorting_1">Twitter</td>
							<td class=" ">Siyaset</td>
							  <td class=" ">@misbahcan</td>
							  <td class="center  ">21.08.2015 Perşembe</td>
						</tr>
					</tbody>
					<tfoot>
					  <tr>
						  <th>Kaynak</th><th>İçerik</th><th>Yazar</th><th class="">Tarih</th> 
					  </tr>
					</tfoot>
				  </table>
				  
              </div>
			  <div>
				<ul id="paginationBlock" class="pagination">
					<li><a href="#">1</a></li>
					<li><a href="#">2</a></li>
					<li><a href="#">3</a></li>
					<li><a href="#">4</a></li>
					<li><a href="#">5</a></li>
				</ul>
			  </div>
              </div>
            </section>
        </div>
	</div>

			  <!--
	<h3>Search Contents</h3>

	<div id="search-form-pane"></div>

	<div id="search-results">

		<h4>Search Results</h4>

		<ul id="search-result-pane"></ul>

		<a href="" id="load-more-link">Load next</a>

	</div>
	-->

<script type="text/javascript">

	$(function() {
		var from = 50;
		$.get('/application/content/searchFormPane', function(result) {
			$("#panel-inside").html(result);
		});
		$('#load-more-link').click(function(e) {
		  loadSearchResults(from);
		  from += 50;
		  return false;
		});
	});

</script>