<div id="search-form">

	<div class="col-md-4">
		<select id="uc_for" name="uc_for[]" multiple>
			<?php foreach($this->keywords as $keyword): ?>
				<option value="<?php echo $keyword; ?>"><?php echo $keyword; ?></option>
			<?php endforeach; ?>
		</select>
	</div>

	<div class="col-md-4">
		<input id="form-keyword-custom" class="form-control" placeholder="Custom Value" />
	</div>
	
	<div class="col-md-4">
		<input type="submit" value="SEARCH" class="btn" id="search-button" />
	</div>

	<!--
	<ul id="keywords">

		
			<li>
				<a href="javascript:void(0)" class="search-keyword" id="form-keyword-<?php echo $keyword; ?>" data-keyword=""></a>
			</li>
		


			<li class="textfield">

				

			</li>

			<li class="submit">

				

			</li>


	</ul>
	-->
	
</div>

<!--
<div id="leftmargin">
	<p><input id="form-keyword-custom" class="form-control" placeholder="Custom Value" /> <input type="submit" value="SEARCH" class="btn" id="search-button" /></p>
</div>
-->

<script type="text/javascript">
/**
$(function() {
	$('.search-keyword').click(function(e) {
	  if($(this).attr('data-selected') == 'selected') {
		$(this).attr('data-selected', '');
		$(this).removeClass('selected-keyword');
	  } else {
		$(this).attr('data-selected', 'selected');
		$(this).addClass('selected-keyword');
	  }
	});
	$('#search-button').click(function(e) {
		loadSearchResults(0);
	});
	function loadSearchResults(from) {
		var items = [];
		$('#search-form>ul').children().each(function(el) {
		  if($(this).children('a').attr('data-selected') == 'selected')
			items.push($(this).children('a').attr('data-keyword'));
		});
		
		if($('#form-keyword-custom').val().length > 2)
		  items.push($('#form-keyword-custom').val());
	  
		$.getJSON('/application/content/searchResultsPane', {keywords: items.join(','), from: from}, function(data) {
			var bodyHtml = "", paginationHtml = "", clas = "";
			$.each(data.body, function(index, element) {
				bodyHtml += '<tr class="gradeA '+element.c+'">';
				bodyHtml += '<td class="typeof">'+element.s+'</td>';
				bodyHtml += '<td class="bodyof">'+element.b+'</td>';
				bodyHtml += '<td class="nameof">'+element.a+'</td>';
				bodyHtml += '<td class="dateof">'+element.t+'</td>';
				bodyHtml += '</tr>';
			});
			$('#insideHtml').html(bodyHtml);
			
			if(data.pageNow > 0) paginationHtml += linkCreator("", (data.pageNow - 1) * 10, "<");
			$.each(data.paginationLinks, function(index, element) {
				clas = "";
				if(element == data.pageNow) clas = ' class="active"';
				paginationHtml += linkCreator(clas, element * 10, element);
			});
			if(data.pageNow < data.pageTotal - 1) paginationHtml += linkCreator("", (data.pageNow + 1) * 10, ">");
			$("#paginationBlock").html(paginationHtml);
			
			$("html, body").animate({ scrollTop: $('#records').offset().top }, 300);
			
		});
	}
	
	function linkCreator(clas, numberData, fromData) {
		return '<li' + clas + '><a from-data="' + numberData + '" class="paglinks">' + fromData + '</a></li>';
	}
	
	$( "#paginationBlock" ).on( "click", ".paglinks", function() {
		var fromData = $(this).attr("from-data");
		loadSearchResults(fromData);
	});
	
});
**/
</script>