<!DOCTYPE html>
<html lang="en">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
  <title>GOSSAMER</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">

  <!-- Bootstrap core CSS -->
    <link href="css/bootstrap.min.css" rel="stylesheet">
    <link href="css/bootstrap-reset.css" rel="stylesheet">
	
    <!--external css-->
    <link href="assets/font-awesome/css/font-awesome.css" rel="stylesheet" />
    <!--<link href="css/navbar-fixed-top.css" rel="stylesheet">-->

      <!-- Custom styles for this template -->
    <link href="css/style.css" rel="stylesheet">
    <link href="css/style-responsive.css" rel="stylesheet" />

    <!-- HTML5 shim and Respond.js IE8 support of HTML5 tooltipss and media queries -->
    <!--[if lt IE 9]>
      <script src="js/html5shiv.js"></script>
      <script src="js/respond.min.js"></script>
    <![endif]-->
	
	<script src="/js/jquery.js"></script>
	
<?php 
/**		
echo $this->headLink() 
	->prependStylesheet($this->basePath('css/style-responsive.css'))
	->prependStylesheet($this->basePath('css/style.css'))
	->prependStylesheet($this->basePath('assets/font-awesome/css/font-awesome.css'))
	->prependStylesheet($this->basePath('css/bootstrap-reset.css'))
    ->prependStylesheet($this->basePath('css/bootstrap.min.css'));
**/
	?>

<?php 
/**
echo $this->headScript()
			->prependFile($this->basePath('js/advanced-form-components.js'))
			->prependFile($this->basePath('assets/jquery-multi-select/js/jquery.multi-select.js'))
			->prependFile($this->basePath('assets/bootstrap-timepicker/js/bootstrap-timepicker.js'))
			->prependFile($this->basePath('assets/bootstrap-colorpicker/js/bootstrap-colorpicker.js'))
			->prependFile($this->basePath('assets/bootstrap-datetimepicker/js/bootstrap-datetimepicker.js'))
			->prependFile($this->basePath('assets/bootstrap-datepicker/js/bootstrap-datepicker.js'))
			->prependFile($this->basePath('assets/fuelux/js/spinner.min.js'))
			->prependFile($this->basePath('js/common-scripts.js'))
			->prependFile($this->basePath('js/dynamic_table_init.js'))
			->prependFile($this->basePath('js/slidebars.min.js'))
			->prependFile($this->basePath('js/respond.min.js'))
			->prependFile($this->basePath('assets/data-tables/DT_bootstrap.js'))
			->prependFile($this->basePath('assets/advanced-datatable/media/js/jquery.dataTables.js'))
			->prependFile($this->basePath('js/jquery.nicescroll.js'))
			->prependFile($this->basePath('js/jquery.scrollTo.min.js'))
			->prependFile($this->basePath('js/jquery.dcjqaccordion.2.7.js'))
            ->prependFile($this->basePath('js/bootstrap.min.js'))
			->prependFile($this->basePath('js/jquery-migrate-1.2.1.min.js'))
			->prependFile($this->basePath('js/jquery-ui-1.9.2.custom.min.js'))
			->prependFile($this->basePath('js/jquery.js'))
            ->prependFile($this->basePath('js/respond.min.js'), 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath('js/html5shiv.min.js'),   'text/javascript', array('conditional' => 'lt IE 9',))
        ; 
		**/ 
		?>
</head>


<body class="full-width">


	<section id="container" class="">

		<!--<div id="header">
		  
			<ul class="menu">
				<li><a href="/stats">Stats</a></li>
				<li><a href="/list">Contents</a></li>
				<li><a href="/keywords">Keywords</a></li>
			</ul>

		</div>-->
		
		
		
		<header class="header white-bg">
          <div class="navbar-header">
              <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                  <span class="fa fa-bars"></span>
              </button>

              <!--logo start-->
              <a href="index.html" class="logo" >Gos<span>samer</span></a>
              <!--logo end-->
              <div class="horizontal-menu navbar-collapse collapse ">
                  <ul class="nav navbar-nav">
                      <li<?php if($this->currentUri == "list"): ?> class="active"<?php endif; ?>><a href="/list">İçerikler</a></li>
                      <li<?php if($this->currentUri == "process"): ?> class="active"<?php endif; ?>><a href="/process">İşlemler</a></li>
                      <li<?php if($this->currentUri == "keywords"): ?> class="active"<?php endif; ?>><a href="/keywords">Raporlar</a></li>
                      <li<?php if($this->currentUri == "stats"): ?> class="active"<?php endif; ?>><a href="/stats">İstatistikler</a></li>
                      
                  </ul>
              </div>
          </div>
		</header>
		
		
		
		
		


		<section id="main-content">
			<section class="wrapper">
		  
				<?php echo $this->content; ?>

			</section>
		</section>
	
	
    <script src="js/jquery-ui-1.9.2.custom.min.js"></script>
    <script src="js/jquery-migrate-1.2.1.min.js"></script>
    <script src="js/bootstrap.min.js"></script>
    <script class="include" type="text/javascript" src="js/jquery.dcjqaccordion.2.7.js"></script>
    <script src="js/jquery.scrollTo.min.js"></script>
    <script src="js/jquery.nicescroll.js" type="text/javascript"></script>
    <script type="text/javascript" language="javascript" src="assets/advanced-datatable/media/js/jquery.dataTables.js"></script>
    <script type="text/javascript" src="assets/data-tables/DT_bootstrap.js"></script>
    <script src="js/respond.min.js" ></script>

    <!--right slidebar-->
    <script src="js/slidebars.min.js"></script>

    <!--dynamic table initialization -->
    <script src="js/dynamic_table_init.js"></script>


    <!--common script for all pages-->
    <script src="js/common-scripts.js"></script>
  
    <!--this page plugins-->

	<script type="text/javascript" src="assets/fuelux/js/spinner.min.js"></script>

	<script type="text/javascript" src="assets/bootstrap-datepicker/js/bootstrap-datepicker.js"></script>
	<script type="text/javascript" src="assets/bootstrap-datetimepicker/js/bootstrap-datetimepicker.js"></script>

	<script type="text/javascript" src="assets/bootstrap-colorpicker/js/bootstrap-colorpicker.js"></script>
	<script type="text/javascript" src="assets/bootstrap-timepicker/js/bootstrap-timepicker.js"></script>
	<script type="text/javascript" src="assets/jquery-multi-select/js/jquery.multi-select.js"></script>

    <script src="js/advanced-form-components.js"></script>

</body>

</html>